#services:
#  mysql:
#    container_name: mysql-2
#    image: mysql
#    ports:
#      - "3307:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: strong_password
#    volumes:
#      - mysql_data:/var/lib/mysql
#
#  nginx:
#    build: ./nginx/
#    ports:
#      - 80:80
#    volumes:
#      - ./src/:/var/www/html/
#
#
#  php:
#    build: ./src/
#    ports:
#      - 9000:9000
#    volumes:
#      - ./src/:/var/www/html/
#  phpmyadmin:
#    container_name: phpmyadmin-2
#    image: phpmyadmin
#    ports:
#      - "8080:80"  # Map port 8080 on the host to port 80 in the container
#    environment:
#      PMA_HOST: mysql-2
#      PMA_PORT: 3306
#      PMA_ARBITRARY: 1
#    depends_on:
#      - mysql
#
#volumes:
#  mysql_data:  # Volume for MySQL data persistence
#
#
services:
   nginx:
     build: ./nginx/
     ports:
       - 80:80
  
     volumes:
         - ./src/:/var/www/html/

   php:
     build: ./src/
     expose:
       - 9000
     volumes:
        - ./src/:/var/www/html/


   db:    
      image: mariadb  
      volumes: 
        -    mysql-data:/var/lib/mysql
      environment:  
       MYSQL_ROOT_PASSWORD: mariadb
       MYSQL_DATABASE: ecomdb 


volumes:
    mysql-data:
