services:
  nginx:
    build: ./nginx/
    ports:
      - 80:80
    volumes:
      - ./Website/:/var/www/html/

  php:
    build: ./Website/
    expose:
      - 9000
    volumes:
      - ./Website/:/var/www/html/

  db:
    image: mariadb
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ciollo123!
      #MYSQL_DATABASE: example_database
      MYSQL_USER: ciollo
      MYSQL_PASSWORD: ciollo123!

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_USER: ciollo
      PMA_PASSWORD: ciollo123!
      PMA_ARBITRARY: 1

volumes:
  mysql-data:
